name = "BPAEMTPReference"
uuid = "379ef2ed-aa07-4523-9a5b-6fc193417d96"
authors = ["Ahmed Elkholy"]
version = "0.1.0"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
