name = "AIMORACatalogs"
uuid = "2b6c9f6e-dc5c-4462-b175-cd3ce62f4f80"
authors = ["Ahmed Elkholy"]
version = "0.1.0"

[deps]
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
