name = "AIMORAReferenceModels"
uuid = "6a268073-c1b2-474c-bd10-49e12d1609a5"
version = "0.1.0"
authors = ["Ahmed Elkholy <ahmed_elkholy@f-eng.tanta.edu.eg>"]
license = "PolyForm-Noncommercial-1.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
